apiVersion: v1
kind: Service
metadata:
  name: api-gateway-linux-service
  labels:
    app: api-gateway-microservice
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-microservice
  ports:
    - port: 8000
      targetPort: 8000