replicaCount: 1

image:
  repository: lazargolomeev/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  ingressClassName: ''

resources:
  {}

nodeSelector: {}

tolerations: []

affinity: {}
